databases:
  - name: Wallet-Watcher
    databaseName: Wallet-Watcher
    user: Wallet-Watcher

services:
  - type: web
    name: Wallet-Watcher
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Wallet-Watcher
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false